
import java.util.ArrayList;
import java.util.Collections;

public class frekanstablecopy extends javax.swing.JFrame {

    ArrayList<Double> mainlist = new ArrayList<>();
    ArrayList<Double> yedeklist = new ArrayList<>();

    public frekanstablecopy() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Frekans Tablosu");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        sinifFrekansı = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        sinifFrekansı1 = new javax.swing.JLabel();
        sinifFrekansı2 = new javax.swing.JLabel();
        sinifFrekansı3 = new javax.swing.JLabel();
        sinifFrekansı4 = new javax.swing.JLabel();
        sinifFrekansı5 = new javax.swing.JLabel();
        sinifFrekansı6 = new javax.swing.JLabel();
        sinifFrekansı7 = new javax.swing.JLabel();
        sinifFrekansı8 = new javax.swing.JLabel();
        sinifFrekansı9 = new javax.swing.JLabel();
        sinifFrekansı10 = new javax.swing.JLabel();
        sinifFrekansı11 = new javax.swing.JLabel();
        sinifFrekansı12 = new javax.swing.JLabel();
        sinifFrekansı13 = new javax.swing.JLabel();
        sinifFrekansı14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        limitAlt = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        sinifFrekansi = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        limitUst = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        sinirAlt = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        sinirUst = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        oransalEklenikFrekans = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        son = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        eklenikFrekans = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        oransalFrekans = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sayiAdedi = new javax.swing.JSpinner();
        veri = new javax.swing.JSpinner();
        ekle = new javax.swing.JButton();
        hesapla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Sınıf Limitleri");

        sinifFrekansı.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sinifFrekansı.setForeground(new java.awt.Color(255, 255, 255));
        sinifFrekansı.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sinifFrekansı.setText("Frekansı");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Sınıf Sınırları");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Noktası");

        sinifFrekansı1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sinifFrekansı1.setForeground(new java.awt.Color(255, 255, 255));
        sinifFrekansı1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sinifFrekansı1.setText("Sınıf");

        sinifFrekansı2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sinifFrekansı2.setForeground(new java.awt.Color(255, 255, 255));
        sinifFrekansı2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sinifFrekansı2.setText("Sınıf");

        sinifFrekansı3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sinifFrekansı3.setForeground(new java.awt.Color(255, 255, 255));
        sinifFrekansı3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sinifFrekansı3.setText("Orta");

        sinifFrekansı4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sinifFrekansı4.setForeground(new java.awt.Color(255, 255, 255));
        sinifFrekansı4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sinifFrekansı4.setText("Eklenik");

        sinifFrekansı5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sinifFrekansı5.setForeground(new java.awt.Color(255, 255, 255));
        sinifFrekansı5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sinifFrekansı5.setText("Frekansı");

        sinifFrekansı6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sinifFrekansı6.setForeground(new java.awt.Color(255, 255, 255));
        sinifFrekansı6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sinifFrekansı6.setText("Frekans");

        sinifFrekansı7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sinifFrekansı7.setForeground(new java.awt.Color(255, 255, 255));
        sinifFrekansı7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sinifFrekansı7.setText("Oransal");

        sinifFrekansı8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sinifFrekansı8.setForeground(new java.awt.Color(255, 255, 255));
        sinifFrekansı8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sinifFrekansı8.setText("Oransal");

        sinifFrekansı9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sinifFrekansı9.setForeground(new java.awt.Color(255, 255, 255));
        sinifFrekansı9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sinifFrekansı9.setText("Eklenik");

        sinifFrekansı10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sinifFrekansı10.setForeground(new java.awt.Color(255, 255, 255));
        sinifFrekansı10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sinifFrekansı10.setText("Frekans");

        sinifFrekansı11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sinifFrekansı11.setForeground(new java.awt.Color(255, 255, 255));
        sinifFrekansı11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sinifFrekansı11.setText("Alt");

        sinifFrekansı12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sinifFrekansı12.setForeground(new java.awt.Color(255, 255, 255));
        sinifFrekansı12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sinifFrekansı12.setText("Üst");

        sinifFrekansı13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sinifFrekansı13.setForeground(new java.awt.Color(255, 255, 255));
        sinifFrekansı13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sinifFrekansı13.setText("Alt");

        sinifFrekansı14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sinifFrekansı14.setForeground(new java.awt.Color(255, 255, 255));
        sinifFrekansı14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sinifFrekansı14.setText("Üst");

        limitAlt.setColumns(20);
        limitAlt.setRows(5);
        limitAlt.setFocusable(false);
        jScrollPane1.setViewportView(limitAlt);

        sinifFrekansi.setColumns(20);
        sinifFrekansi.setRows(5);
        sinifFrekansi.setFocusable(false);
        jScrollPane2.setViewportView(sinifFrekansi);

        limitUst.setColumns(20);
        limitUst.setRows(5);
        limitUst.setFocusable(false);
        jScrollPane3.setViewportView(limitUst);

        sinirAlt.setColumns(20);
        sinirAlt.setRows(5);
        sinirAlt.setFocusable(false);
        jScrollPane4.setViewportView(sinirAlt);

        sinirUst.setColumns(20);
        sinirUst.setRows(5);
        sinirUst.setFocusable(false);
        jScrollPane5.setViewportView(sinirUst);

        oransalEklenikFrekans.setColumns(20);
        oransalEklenikFrekans.setRows(5);
        oransalEklenikFrekans.setFocusable(false);
        jScrollPane6.setViewportView(oransalEklenikFrekans);

        son.setColumns(20);
        son.setRows(5);
        son.setFocusable(false);
        jScrollPane7.setViewportView(son);

        eklenikFrekans.setColumns(20);
        eklenikFrekans.setRows(5);
        eklenikFrekans.setFocusable(false);
        jScrollPane8.setViewportView(eklenikFrekans);

        oransalFrekans.setColumns(20);
        oransalFrekans.setRows(5);
        oransalFrekans.setFocusable(false);
        jScrollPane9.setViewportView(oransalFrekans);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("n         :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Veri    :");

        ekle.setBackground(new java.awt.Color(255, 153, 0));
        ekle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ekle.setForeground(new java.awt.Color(0, 0, 255));
        ekle.setText("Ekle");
        ekle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleActionPerformed(evt);
            }
        });

        hesapla.setBackground(new java.awt.Color(0, 0, 255));
        hesapla.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hesapla.setForeground(new java.awt.Color(255, 153, 0));
        hesapla.setText("Hesapla");
        hesapla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hesapla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hesaplaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sinifFrekansı11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sinifFrekansı12, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(sinifFrekansı13, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sinifFrekansı14, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sinifFrekansı, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(362, 362, 362)
                                        .addComponent(sinifFrekansı1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sayiAdedi, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(veri, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ekle, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                            .addComponent(hesapla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(0, 17, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sinifFrekansı2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sinifFrekansı3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sinifFrekansı4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sinifFrekansı5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sinifFrekansı7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sinifFrekansı6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sinifFrekansı9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sinifFrekansı10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sinifFrekansı8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ekle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addComponent(sayiAdedi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(veri)
                                .addGap(11, 11, 11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sinifFrekansı2)
                            .addComponent(sinifFrekansı8)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(hesapla, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sinifFrekansı1)
                    .addComponent(sinifFrekansı3)
                    .addComponent(sinifFrekansı7)
                    .addComponent(sinifFrekansı9)
                    .addComponent(sinifFrekansı4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(sinifFrekansı)
                    .addComponent(jLabel12)
                    .addComponent(sinifFrekansı5)
                    .addComponent(sinifFrekansı6)
                    .addComponent(sinifFrekansı10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sinifFrekansı11)
                    .addComponent(sinifFrekansı12)
                    .addComponent(sinifFrekansı13)
                    .addComponent(sinifFrekansı14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleActionPerformed
        double alinanVeri = (int) veri.getValue();
        mainlist.add(alinanVeri);
        yedeklist.add(alinanVeri);

    }//GEN-LAST:event_ekleActionPerformed

    private void hesaplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hesaplaActionPerformed
        double n = (Integer) sayiAdedi.getValue();
        Collections.sort(mainlist);
        double L = mainlist.get(mainlist.size() - 1);
        double S = mainlist.get(0);
        double R = L - S;
        double k = (int) Math.ceil(Math.sqrt(n));
        double h = (int) Math.ceil(R / k);

        ArrayList<Double> limitAltArr = new ArrayList<>();
        ArrayList<Double> limitUstArr = new ArrayList<>();
        ArrayList<Double> sinifAltArr = new ArrayList<>();
        ArrayList<Double> sinifUstArr = new ArrayList<>();
        ArrayList<Double> sinifFrekansArr = new ArrayList<>();
        ArrayList<Double> sonArr = new ArrayList<>();
        ArrayList<Double> eklenikFrekArr = new ArrayList<>();
        ArrayList<Double> oransalFrekArr = new ArrayList<>();
        ArrayList<Double> oefArr = new ArrayList<>();

        //alt limit dizisini doldurma
        for (int i = 0; i < k; i++) {
            limitAltArr.add(mainlist.get(0) + (i * h));
        }

        // üst limit dizisini doldurma
        for (int i = 0; i < k; i++) {
            limitUstArr.add(limitAltArr.get(1) - 1 + (i * h));
        }

        // alt sınıf dizisini doldurma
        for (int i = 0; i < k; i++) {
            sinifAltArr.add(mainlist.get(0) + (i * h) - 0.5);
        }

        //üst sınıf dizisini doldurma
        for (int i = 0; i < k; i++) {
            sinifUstArr.add(limitUstArr.get(0) + 0.5 + (i * h));
        }

        //sinif frekans dizisini doldurma
        double rep;
        for (int i = 0; i < k; i++) {
            rep = 0;
            for (int j = 0; j < n; j++) {
                if (mainlist.get(j) >= sinifAltArr.get(i) && mainlist.get(j) <= sinifUstArr.get(i)) {
                    rep++;
                }
            }
            sinifFrekansArr.add(rep);
        }

        //sınıf orta noktası dizisi doldurma
        double ort = 0;
        for (int i = 0; i < k; i++) {
            ort = (limitAltArr.get(i) + limitUstArr.get(i)) / 2;
            sonArr.add(ort);
        }

        //eklenik frekans dizisi doldurma
        eklenikFrekArr.add(sinifFrekansArr.get(0));
        for (int i = 1; i < k; i++) {
            eklenikFrekArr.add(sinifFrekansArr.get(i) + eklenikFrekArr.get(i - 1));
        }

        //oransal frekans dizisini doldurma
        for (int i = 0; i < k; i++) {
            oransalFrekArr.add(sinifFrekansArr.get(i) / n);
        }

        //oransal eklenik frekans dizisini doldurma
        for (int i = 0; i < k; i++) {
            oefArr.add(eklenikFrekArr.get(i) / n);
        }

        for (int i = 0; i < k; i++) {
            limitAlt.append(limitAltArr.get(i) + "\n");
            limitUst.append(limitUstArr.get(i) + "\n");
            sinirAlt.append(sinifAltArr.get(i) + "\n");
            sinirUst.append(sinifUstArr.get(i) + "\n");
            sinifFrekansi.append(sinifFrekansArr.get(i) + "\n");
            son.append(sonArr.get(i) + "\n");
            eklenikFrekans.append(eklenikFrekArr.get(i) + "\n");
            oransalFrekans.append(oransalFrekArr.get(i) + "\n");
            oransalEklenikFrekans.append(oefArr.get(i) + "\n");
        }


    }//GEN-LAST:event_hesaplaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frekanstablecopy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frekanstablecopy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frekanstablecopy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frekanstablecopy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frekanstablecopy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ekle;
    private javax.swing.JTextArea eklenikFrekans;
    private javax.swing.JButton hesapla;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea limitAlt;
    private javax.swing.JTextArea limitUst;
    private javax.swing.JTextArea oransalEklenikFrekans;
    private javax.swing.JTextArea oransalFrekans;
    private javax.swing.JSpinner sayiAdedi;
    private javax.swing.JTextArea sinifFrekansi;
    private javax.swing.JLabel sinifFrekansı;
    private javax.swing.JLabel sinifFrekansı1;
    private javax.swing.JLabel sinifFrekansı10;
    private javax.swing.JLabel sinifFrekansı11;
    private javax.swing.JLabel sinifFrekansı12;
    private javax.swing.JLabel sinifFrekansı13;
    private javax.swing.JLabel sinifFrekansı14;
    private javax.swing.JLabel sinifFrekansı2;
    private javax.swing.JLabel sinifFrekansı3;
    private javax.swing.JLabel sinifFrekansı4;
    private javax.swing.JLabel sinifFrekansı5;
    private javax.swing.JLabel sinifFrekansı6;
    private javax.swing.JLabel sinifFrekansı7;
    private javax.swing.JLabel sinifFrekansı8;
    private javax.swing.JLabel sinifFrekansı9;
    private javax.swing.JTextArea sinirAlt;
    private javax.swing.JTextArea sinirUst;
    private javax.swing.JTextArea son;
    private javax.swing.JSpinner veri;
    // End of variables declaration//GEN-END:variables
}
